'use client'

// Generated by wasm-pack. Run once:
//   bash greek-morph/fetch-data.sh
//   cd greek-morph && wasm-pack build --target web --out-dir ../public/greek-morph

export type ParseEntry = {
  lemma: string
  pos: string
  parsing: string
  parsing_human: string
  gloss: string
  inflected_gloss: string
  tense_note: string | null
  voice_note: string | null
  mood_note: string | null
  case_note: string | null
}

type WasmMod = {
  default: (wasmPath?: string) => Promise<void>
  lookup: (word: string) => ParseEntry[]
  is_greek: (word: string) => boolean
}

let mod: WasmMod | null = null
let promise: Promise<WasmMod | null> | null = null

export async function initGreekMorph(): Promise<WasmMod | null> {
  if (mod) return mod
  if (promise) return promise

  promise = (async () => {
    try {
      // webpackIgnore: loaded from /public at runtime, not bundled
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore — runtime path not resolvable at compile time
      const m = await import(/* webpackIgnore: true */ '/greek-morph/greek_morph.js') as WasmMod
      await m.default('/greek-morph/greek_morph_bg.wasm')
      mod = m
      return mod
    } catch {
      // WASM not built yet or not deployed — components degrade gracefully
      return null
    }
  })()

  return promise
}

export async function lookupWord(word: string): Promise<ParseEntry[]> {
  const m = await initGreekMorph()
  if (!m) return []
  try {
    return m.lookup(word) ?? []
  } catch {
    return []
  }
}

// Client-side Greek Unicode detection (mirrors Rust is_greek())
export function isGreek(word: string): boolean {
  return /[Ͱ-Ͽἀ-῿]/.test(word)
}

// Split a text string into Greek/non-Greek segments for auto-wrapping
export function splitGreek(text: string): Array<{ text: string; greek: boolean }> {
  const segments: Array<{ text: string; greek: boolean }> = []
  // Split on word boundaries, preserving whitespace and punctuation
  const parts = text.split(/(\s+)/)

  for (const part of parts) {
    if (!part) continue
    const greek = isGreek(part)
    if (segments.length > 0 && segments[segments.length - 1].greek === greek) {
      segments[segments.length - 1].text += part
    } else {
      segments.push({ text: part, greek })
    }
  }

  return segments
}
