-- Sermon publishing, ported from the Crosswalk site (its migrations 0003,
-- 0010, 0013 through 0023, 0037 through 0039 collapsed into one file).
-- Idempotent. RLS on, explicit grants to service_role.

-- Staff action log -----------------------------------------------------------
create table if not exists public.audit_log (
  id         bigint generated always as identity primary key,
  actor      text not null,
  action     text not null,
  created_at timestamptz not null default now()
);
alter table public.audit_log enable row level security;
grant all on public.audit_log to service_role;

-- Storage bucket every sermon asset lives in (artwork, hero stills, cutouts,
-- speaker portraits, study guides) under a sermons/ prefix.
insert into storage.buckets (id, name, public)
  values ('content-intake', 'content-intake', true)
  on conflict (id) do nothing;

-- Series ----------------------------------------------------------------------
create table if not exists public.sermon_series (
  id             bigint generated by default as identity primary key,
  slug           text unique not null,
  title          text not null,
  subtitle       text,                        -- holds the scripture the series covers
  description    text,
  artwork_url    text,                        -- 1920x1080 poster
  background_url text,                        -- backdrop behind the speaker cutout
  banner_url     text,                        -- wide header banner
  status         text not null default 'draft',   -- 'published' | 'draft' | 'scheduled'
  scheduled_at   timestamptz,
  starts_on      date,
  ends_on        date,
  sort_order     int not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
alter table public.sermon_series enable row level security;
drop policy if exists "sermon_series public read" on public.sermon_series;
create policy "sermon_series public read" on public.sermon_series for select using (true);
drop policy if exists "sermon_series service write" on public.sermon_series;
create policy "sermon_series service write" on public.sermon_series for all using (auth.role() = 'service_role');
grant select on public.sermon_series to anon, authenticated;
grant all on public.sermon_series to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Sermons ---------------------------------------------------------------------
create table if not exists public.sermons (
  id                    bigint generated always as identity primary key,
  slug                  text not null unique,
  title                 text not null,
  subtitle              text,
  series                text,                 -- legacy text label, kept in sync with series_id
  series_id             bigint references public.sermon_series(id) on delete set null,
  speaker               text not null default 'Austin W. Duncan',
  speakers              text[],
  passage               text,
  scripture             text[],
  topics                text[],
  week                  smallint,
  date                  date,
  youtube_id            text,
  youtube_id_full       text,
  canonical_url         text,
  summary               text,
  description           text,
  body                  text not null default '',
  document_url          text,
  document_name         text,
  web_link_1_url        text,
  web_link_1_label      text,
  web_link_2_url        text,
  web_link_2_label      text,
  artwork_url           text,
  hero_still_url        text,
  hero_still_candidates text[],
  hero_cutout_url       text,
  hero_focal_x          smallint,
  hero_focal_y          smallint,
  hero_target_x         smallint,
  hero_target_y         smallint,
  hero_zoom             real,
  published             boolean not null default false,
  status                text not null default 'draft',   -- 'published' | 'draft' | 'scheduled'
  scheduled_at          timestamptz,
  sort_order            int not null default 0,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index if not exists sermons_series_id_idx on public.sermons (series_id);
alter table public.sermons enable row level security;
drop policy if exists "public read published" on public.sermons;
create policy "public read published" on public.sermons
  for select using (
    published = true
    or status = 'published'
    or (status = 'scheduled' and scheduled_at is not null and scheduled_at <= now())
  );
drop policy if exists "service write" on public.sermons;
create policy "service write" on public.sermons
  for all using (auth.role() = 'service_role');
grant select on public.sermons to anon, authenticated;
grant all on public.sermons to service_role;

-- Normalized scripture references, one row per chip, for the Scripture Atlas
create table if not exists public.sermon_scripture_refs (
  id          bigint generated always as identity primary key,
  sermon_id   bigint not null references public.sermons(id) on delete cascade,
  book        text not null,
  book_order  smallint not null,
  chapter     smallint,
  verse_start smallint,
  verse_end   smallint,
  ref_text    text,
  created_at  timestamptz not null default now()
);
create index if not exists sermon_scripture_refs_sermon on public.sermon_scripture_refs (sermon_id);
create index if not exists sermon_scripture_refs_book on public.sermon_scripture_refs (book_order, chapter);
alter table public.sermon_scripture_refs enable row level security;
drop policy if exists "public read scripture refs" on public.sermon_scripture_refs;
create policy "public read scripture refs" on public.sermon_scripture_refs for select using (true);
drop policy if exists "scripture refs service write" on public.sermon_scripture_refs;
create policy "scripture refs service write" on public.sermon_scripture_refs for all using (auth.role() = 'service_role');
grant select on public.sermon_scripture_refs to anon, authenticated;
grant all on public.sermon_scripture_refs to service_role;

-- Speakers --------------------------------------------------------------------
create table if not exists public.speakers (
  id         bigint generated always as identity primary key,
  slug       text not null unique,
  name       text not null,
  role       text,
  photo_url  text,
  bio        text,
  sort_order int not null default 0,
  published  boolean not null default true,
  created_at timestamptz not null default now()
);
grant usage on schema public to anon, authenticated, service_role;
grant select on public.speakers to anon, authenticated;
grant all on public.speakers to service_role;
alter table public.speakers enable row level security;
drop policy if exists "public read published speakers" on public.speakers;
create policy "public read published speakers" on public.speakers for select using (published = true);
drop policy if exists "speakers service write" on public.speakers;
create policy "speakers service write" on public.speakers for all using (auth.role() = 'service_role');

grant usage, select on all sequences in schema public to service_role;
notify pgrst, 'reload schema';
